# Change these first
owner: noclocks
repo: noclocks-uptime
user-agent: noclocks

sites:
  - name: Domain
    url: https://noclocks.dev
    icon: https://noclocks.dev/favicon.ico
  - name: Website
    url: https://noclocks.dev
  - name: Online Store
    url: https://store.noclocks.dev
  - name: Development Store
    url: https://devstore.noclocks.dev
  - name: Development Store Accounts
    url: https://accounts.store.noclocks.dev
  - name: Blog
    url: https://blog.noclocks.dev
  - name: Medium
    url: https://medium.noclocks.dev/
  - name: Testimonials
    url: https://testimonials.noclocks.dev
  - name: EnvShare
    url: https://envshare.noclocks.dev
  - name: DevDocs (Demo)
    url: https://devdocs.noclocks.dev

assignees:
  - jimbrig
  - phoward38
